// Generated by scripts/fetch-dept-offerings.mjs — do not edit by hand.
// Source: UCSD registrar, "Projected Course Offerings for Fall 2026"
// https://docs.google.com/spreadsheets/d/1gjezK4NlqWyZzjSFd2qGTcCgM4YduZLL/edit?gid=881933084

export interface DepartmentOffering {
  /** Department name as the registrar lists it. */
  department: string;
  /** Subject codes the department owns. */
  subjects: string[];
  /** Where the department publishes its own tentative offerings. */
  url: string | null;
  /** Cell text, when it describes the link rather than repeating it. */
  label: string | null;
  /** The registrar's caveat for this row, where there is one. */
  note: string | null;
}

/** The registrar's standing caveat for every row in this table. */
export const OFFERINGS_NOTICE =
  "Due to the launch of the Triton Student System (TSS) in July 2026, the Schedule of Classes for Fall 2026 enrollment will not be published until mid-July. You can use the below information to find projected course offerings for departments. This information is for tentative planning purposes only and is subject to change.";

export const OFFERINGS_SOURCE = {
  name: 'UCSD registrar, "Projected Course Offerings for Fall 2026"',
  url: "https://docs.google.com/spreadsheets/d/1gjezK4NlqWyZzjSFd2qGTcCgM4YduZLL/edit?gid=881933084",
  retrieved: "2026-08-23",
} as const;

export const DEPARTMENT_OFFERINGS: DepartmentOffering[] = [
  {
    department: "Academic Internship Program",
    subjects: ["AIP"],
    url: "https://docs.google.com/document/d/1UgfUjs_Xbj3eizuMloz0RueXwW84kEVu5peV6yyCZQk/edit?tab=t.0",
    label: "For the Web: 2026-2027 Tentative Course Schedule",
    note: null,
  },
  {
    department: "Analytical Writing Program",
    subjects: ["AWP"],
    url: null,
    label: null,
    note: "FA26: AWP-003 & AWP-004B (2 sections); WI27: AWP 3 & AWP 4A; SP27: AWP 3 & AWP 4A (2-3 sections) & AWP 4B",
  },
  {
    department: "Anthropology",
    subjects: ["ANBI", "ANAR", "ANTH", "ANSC"],
    url: "https://anthropology.ucsd.edu/undergraduate-studies/courses/index.html",
    label: null,
    note: null,
  },
  {
    department: "Asian American and Pacific Islander Studies",
    subjects: ["AAPI"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Astronomy and Astrophysics",
    subjects: ["ASTR"],
    url: "https://astro.ucsd.edu/undergraduate/courses/index.html",
    label: null,
    note: null,
  },
  {
    department: "Bioengineering",
    subjects: ["BENG"],
    url: "https://be.ucsd.edu/undergraduate-course-offerings",
    label: "Undergraduate Course Offerings | Shu Chien - Gene Lay Department of Bioengineering",
    note: null,
  },
  {
    department: "Biology",
    subjects: ["BIEB", "BICD", "BIPN", "BIBC", "BILD", "BIMM", "BISP"],
    url: "https://biology.ucsd.edu/education/undergrad/course/course-offerings.html",
    label: "2026-27 Course Offerings",
    note: null,
  },
  {
    department: "Black Diaspora and African American Studies",
    subjects: ["AAS"],
    url: "https://bdaas.ucsd.edu/courses/index.html",
    label: null,
    note: null,
  },
  {
    department: "Chemical Engineering",
    subjects: ["CENG"],
    url: "https://cne.ucsd.edu/undergrad-programs/undergraduate-academic-planning",
    label: null,
    note: "26-27 wlill be posted here soon",
  },
  {
    department: "Chemistry and Biochemistry",
    subjects: ["CHEM"],
    url: "https://chemistry.ucsd.edu/ext/ugcourses.html?year=2025-2026",
    label: null,
    note: "26-27 offerings will post soon.",
  },
  {
    department: "Chicanx and Latinx Studies",
    subjects: ["CLX"],
    url: "https://cls.ucsd.edu/courses/course-offerings.html",
    label: null,
    note: "26-27 offerings posted late Spring/early summer",
  },
  {
    department: "Chinese Studies",
    subjects: ["CHIN"],
    url: "https://chinesestudies.ucsd.edu/courses/course-offerings.html",
    label: null,
    note: "26-27 offerings posted late Spring/early summer",
  },
  {
    department: "Classical Studies",
    subjects: ["CLAS"],
    url: "https://iah.ucsd.edu/academics/classical-studies/index.html",
    label: null,
    note: "For 26-27 AY, this will be updated mid-June 2026",
  },
  {
    department: "Climate Change Studies",
    subjects: ["CCS"],
    url: "https://scripps.ucsd.edu/education/courses",
    label: null,
    note: "List is updated when new information is available. All listings are tentative.",
  },
  {
    department: "Cognitive Science",
    subjects: ["COGS"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Communication",
    subjects: ["COMM"],
    url: "https://communication.ucsd.edu/undergrad/courses/index.html",
    label: null,
    note: "26-27 now posted",
  },
  {
    department: "Computational Social Science",
    subjects: ["CSS"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Computer Science and Engineering",
    subjects: ["CSE"],
    url: "https://cse.ucsd.edu/undergraduate/tentative-course-offerings",
    label: null,
    note: "Will be updated by 4/16",
  },
  {
    department: "Critical Community Engagement",
    subjects: ["CCE"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Critical Gender Studies",
    subjects: ["CGS"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Culture, Art & Technology",
    subjects: ["CAT"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Data Science",
    subjects: ["DSC"],
    url: "https://datascience.ucsd.edu/current-students/course-offerings/",
    label: null,
    note: "For 26-27 AY, this will be updated around mid-June 26",
  },
  {
    department: "Design",
    subjects: ["DSGN"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Dimensions of Culture",
    subjects: ["DOC"],
    url: "https://marshall.ucsd.edu/doc/index.html",
    label: "DOC 1 and DOC 100D - https://marshall.ucsd.edu/doc/index.html",
    note: "FA26: DOC 1 and DOC 100D, WI27: DOC 2, SP27: DOC 3. Will be updated May/June",
  },
  {
    department: "Economics",
    subjects: ["ECON"],
    url: "https://economics.ucsd.edu/undergraduate-program/resources/courses/index.html",
    label: null,
    note: "For 26-27 AY, this will be updated around mid-June 26",
  },
  {
    department: "Education Studies",
    subjects: ["EDS"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Electrical and Computer Engineering",
    subjects: ["ECE"],
    url: "https://ece.ucsd.edu/ece-tentative-course-list",
    label: null,
    note: null,
  },
  {
    department: "Engineering",
    subjects: ["ENG"],
    url: null,
    label: "ENG 5, ENG 10, ENG 15, ENG 20",
    note: null,
  },
  {
    department: "Environmental Studies",
    subjects: ["ENVR"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Environmental Systems Program",
    subjects: ["ESYS"],
    url: "https://scripps.ucsd.edu/education/courses",
    label: null,
    note: "List is updated when new information is available. All listings are tentative.",
  },
  {
    department: "Ethnic Studies",
    subjects: ["ETHN"],
    url: "https://ethnicstudies.ucsd.edu/schedule/index.html",
    label: "ETHN Schedules",
    note: "Tentative Undergraduate ETHN Schedule for 2026-2027",
  },
  {
    department: "Film Studies",
    subjects: ["FILM"],
    url: "https://iah.ucsd.edu/academics/film-studies/index.html",
    label: null,
    note: "For 26-27 AY, this will be updated mid-June 2026. For FILM-specific classes, for FA26 FILM 71, 72, 73, 87, and 179 will be offered.",
  },
  {
    department: "Global Health",
    subjects: ["GLBH"],
    url: "https://globalhealthprogram.ucsd.edu/undergraduate-program/courses/index.html",
    label: null,
    note: null,
  },
  {
    department: "Global South Studies",
    subjects: ["GSS"],
    url: "https://iah.ucsd.edu/academics/global-south-studies/index.html",
    label: null,
    note: "26-27 offerings posted late Spring/early summer",
  },
  {
    department: "History",
    subjects: ["HITO", "HIAF", "HIEA", "HIEU", "HILA", "HISA", "HISC", "HINE", "HIUS", "HILD"],
    url: "https://history.ucsd.edu/courses/courses-fall.html",
    label: null,
    note: "26-27 offerings will post soon.",
  },
  {
    department: "Human Developmental Sciences",
    subjects: ["HDS"],
    url: "https://hdsciences.ucsd.edu/courses/course-offerings/index.html",
    label: null,
    note: "Updated Mid spring (HDS -specific classes updated sooner)",
  },
  {
    department: "Humanities",
    subjects: ["HUM"],
    url: "https://revelle.ucsd.edu/humanities/courses/index.html",
    label: null,
    note: "Updated beginning of Spring.",
  },
  {
    department: "International Studies",
    subjects: ["INTL"],
    url: null,
    label: "INTL100, INTL101, INTL102 INTL190.",
    note: null,
  },
  {
    department: "Japanese Studies",
    subjects: ["JAPN"],
    url: "https://japan.ucsd.edu/courses/courses-offerings.html",
    label: null,
    note: null,
  },
  {
    department: "Jewish Studies",
    subjects: ["JWSP"],
    url: "https://jewishstudies.ucsd.edu/undergraduate/courses.html",
    label: null,
    note: "26-27 offerings posted late Spring/early summer",
  },
  {
    department: "Latin American Studies",
    subjects: ["LATI"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Law and Society",
    subjects: ["LAWS"],
    url: null,
    label: null,
    note: null,
  },
  {
    department: "Linguistics",
    subjects: ["LIAB", "LIDS", "LIFR", "LIGM", "LIGN", "LIHL", "LIIT", "LIPO", "LISL", "LISP"],
    url: "https://linguistics.ucsd.edu/undergrad/courses/index.html",
    label: null,
    note: null,
  },
  {
    department: "Literature",
    subjects: ["LTAM", "LTAF", "LTCO", "LTCS", "LTEA", "LTEN", "LTEU", "LTFR", "LTGK", "LTGM", "LTIT", "LTKO", "LTLA", "LTRU", "LTSP", "LTTH", "LTWL", "LTWR"],
    url: "https://literature.ucsd.edu/courses/courseofferings/3qplansec2027.html",
    label: null,
    note: null,
  },
  {
    department: "Making of the Modern World",
    subjects: ["MMW"],
    url: "https://roosevelt.ucsd.edu/mmw/courses/index.html",
    label: null,
    note: null,
  },
  {
    department: "Mathematics",
    subjects: ["MATH", "MSED"],
    url: "https://math.ucsd.edu/students/planned-course-offerings",
    label: "MATH: https://math.ucsd.edu/students/planned-course-offerings; MSED- no UG courses offered",
    note: "2026-27 available now",
  },
  {
    department: "Mechanical and Aerospace Engineering",
    subjects: ["MAE"],
    url: "https://mae.ucsd.edu/courses",
    label: null,
    note: null,
  },
  {
    department: "Muir College Writing Program",
    subjects: ["MCWP"],
    url: null,
    label: "MCWP-040, 040R, 050, and 125",
    note: "Website will be updated with topics before enrollment if possible.",
  },
  {
    department: "Music",
    subjects: ["MUS"],
    url: "https://music-web.ucsd.edu/ugrad/cms_courses_offered.php",
    label: null,
    note: "Will be updated for 2026-27 AY in late Spring",
  },
  {
    department: "Nanoengineering",
    subjects: ["NANO"],
    url: "https://cne.ucsd.edu/undergrad-programs/undergraduate-academic-planning",
    label: null,
    note: "26-27 will be posted here soon",
  },
  {
    department: "Philosophy",
    subjects: ["PHIL"],
    url: "https://philosophy.ucsd.edu/courses/year-at-a-glance-26-27.html",
    label: null,
    note: null,
  },
  {
    department: "Physics",
    subjects: ["PHYS"],
    url: "https://physics.ucsd.edu/students/courseofferings",
    label: null,
    note: "Days, times, locations are not yet available.",
  },
  {
    department: "Political Science",
    subjects: ["POLI"],
    url: "https://polisci.ucsd.edu/undergrad/political-science-courses/index.html",
    label: null,
    note: "Click the first link on this page titled \"Political Science Tentative Course Offerings for 2026-2027\"",
  },
  {
    department: "Psychology",
    subjects: ["PSYC"],
    url: "https://psychology.ucsd.edu/undergraduate-program/courses/2026-2027-courses.html",
    label: null,
    note: null,
  },
  {
    department: "Public Health",
    subjects: ["PH"],
    url: "https://ph.ucsd.edu/undergrad/courses/enrollment/fall.html",
    label: null,
    note: "we WILL have FA26 available soon; currently FA25 is listed",
  },
  {
    department: "Rady School of Management",
    subjects: ["MGT"],
    url: "https://rady.ucsd.edu/programs/undergraduate/resources/courses.html",
    label: null,
    note: "Should be updated for '26-'27 in late April or May (will likely be similar to the '25-'26 tentative schedule)",
  },
  {
    department: "Religion, Program for the Study of",
    subjects: ["RELI"],
    url: "https://religion.ucsd.edu/undergraduate/courses/index.html",
    label: null,
    note: null,
  },
  {
    department: "Scripps Institution of Oceanography",
    subjects: ["SIO"],
    url: "https://scripps.ucsd.edu/education/courses",
    label: null,
    note: "List is updated when new information is available. All listings are tentative.",
  },
  {
    department: "Sociology",
    subjects: ["SOCI"],
    url: "https://www.sociology.ucsd.edu/undergraduate/courses.html",
    label: null,
    note: "Sociology Annual Schedule",
  },
  {
    department: "Structural Engineering",
    subjects: ["SE"],
    url: "https://se.ucsd.edu/academics/undergraduate-program/course-offerings",
    label: null,
    note: "26-27 Calendar year updated; SU26 calendar available",
  },
  {
    department: "Synthesis",
    subjects: ["SYN"],
    url: "https://seventh.ucsd.edu/synthesis-program/index.html",
    label: null,
    note: null,
  },
  {
    department: "Theatre and Dance",
    subjects: ["TDAC", "TDDE", "TDDM", "TDDR", "TDGE", "TDHT", "TDMV", "TDPF", "TDPR", "TDPW", "TDTR"],
    url: "https://docs.google.com/spreadsheets/d/1RynReK8ApDs0CNPIhn2crU0U1DNsrlC1uTOSxK7OhSE/edit?usp=sharing",
    label: "Theatre & Dance 2026-27 Annual Offerings for Students",
    note: null,
  },
  {
    department: "Urban Studies and Planning",
    subjects: ["USP"],
    url: "https://docs.google.com/spreadsheets/d/1V1tNPo5nLCx2PBCPf-ncf72-VqGE46rc1clMVk_7n2s/edit?usp=sharing",
    label: null,
    note: null,
  },
  {
    department: "Visual Arts",
    subjects: ["VIS"],
    url: "https://visarts.ucsd.edu/undergrad/annual-schedule.html",
    label: null,
    note: "Will be updated in mid-spring",
  },
  {
    department: "Warren College Writing Program",
    subjects: ["WCWP"],
    url: null,
    label: "WCWP 10A, 10B, and 100",
    note: null,
  },
];

const BY_SUBJECT = new Map<string, DepartmentOffering>();
for (const entry of DEPARTMENT_OFFERINGS) {
  for (const code of entry.subjects) if (!BY_SUBJECT.has(code)) BY_SUBJECT.set(code, entry);
}

/** The department listing that covers a subject code, if the registrar names one. */
export function offeringsForSubject(code: string): DepartmentOffering | null {
  return BY_SUBJECT.get(code.toUpperCase()) ?? null;
}

/** The first listing among a department's subject codes that carries a link. */
export function offeringsForSubjects(codes: string[]): DepartmentOffering | null {
  for (const code of codes) {
    const hit = offeringsForSubject(code);
    if (hit && hit.url) return hit;
  }
  for (const code of codes) {
    const hit = offeringsForSubject(code);
    if (hit) return hit;
  }
  return null;
}
